name: Publish project to Puzzle Maven

on:
  workflow_call:
    secrets:
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
      PLUGIN_SECRET_KEY:
        required: true
      GPG_SECRET_KEY_ID:
        required: true
      GPG_PASSPHRASE:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MAVEN_URL: ${{ vars.MAVEN_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14'

      - name: Build project
        run: gradle build

      - name: Publish to PuzzleHQsMaven
        if: ${{ env.MAVEN_NAME && env.MAVEN_SECRET && env.MAVEN_URL}}
        run: gradle publishMavenPublicationToPuzzleHQsMavenRepository
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token secret (password)
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }} # token secret (password)
          MAVEN_URL: ${{ env.MAVEN_URL }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PLUGIN_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_SECRET_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_REF: ${{ github.ref }}

