name: Publish project to Maven repository

on:
  workflow_call:
    inputs:
      TAG_NAME:
        required: true
        type: string
    secrets:
      MAVEN_CENTRAL_USERNAME:
        required: true
      MAVEN_CENTRAL_PASSWORD:
        required: true
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
      PLUGIN_SECRET_KEY:
        required: true
      GPG_SECRET_KEY_ID:
        required: true
      GPG_PASSPHRASE:
        required: true

jobs:
  maven-central-publish:
    uses: PuzzlesHQ/Puzzles-Workflows/.github/workflows/maven-central-publishing.yml@main
    secrets: inherit
